### ISSUE TITLE
Allow sorting by modification date

### ISSUE THREAD

**Issue by smathot** [dschreij/QOpenScienceFramework#12]
As my number of project grows, I've noticed that it sometimes takes a moment before I've found my project in the explorer. Would it be possible to show the modification date for each project as a column, so that the user can sort by modification date?

**Comment by dschreij** [comment]
Yes that should be easily possible and is a good idea. I also plan on making a filter box, in which users can enter a string to (partially) match with project and file names. All non-matching tree items should then be hidden.

**Comment by dschreij** [comment]
That was easy enough. The data was readily available in the API response and could directly be used.

I just pushed v1.2.2 to our various channels. This shows columns in the tree with Created and Modified, where applicable. Can you check if this works for you?

If so, please close the issue ;)

**Comment by smathot** [comment]
Beautiful! Yes, it works.
