### ISSUE TITLE
Cannot create folder in osfstorage

### ISSUE THREAD

**Issue by smathot** [dschreij/QOpenScienceFramework#16]
If I try to create a folder through OSF explorer, I consistently get the error message below. This happens both when I create a subfolder and a top-level folder.

![image](https://user-images.githubusercontent.com/594936/47208920-669ab880-d38f-11e8-9879-809b65123203.png)

**Comment by dschreij** [comment]
It would seem that there was a small breaking change in the API, which now expects an additional `length` parameter, but I can find no trace of this in the Waterbutler docs: https://waterbutler.readthedocs.io/en/latest/api.html#v1-api (section `Create Subfolder (folders)`). Possibly the change was unintentional? Shall we notify the waterbutler guys of this?

**Comment by smathot** [comment]
> Shall we notify the waterbutler guys of this?

Yes, but I see that you've already done that!

**Comment by felliott** [comment]
I just tried to replicate this with a bucket in the German region and didn't encounter this error.  Are you including any other headers in the request?

**Comment by dschreij** [comment]
Not that I know of, except for the OAuth bearer token maybe?

**Comment by dschreij** [comment]
Did the HTTP request type maybe change? From PUT to PATCH, or similar?

**Comment by dschreij** [comment]
I can reproduce the error @felliott.

<img width="1039" alt="screen shot 2018-10-22 at 13 33 09" src="https://user-images.githubusercontent.com/689044/47290319-25a8db00-d5ff-11e8-87cd-907a86c9fe9e.png">

I don't send any extra headers except the authentication token.

Any suggestions where to look? Can you maybe find out what triggers this error message? (an empty request body maybe?)

**Comment by felliott** [comment]
It's not something we handle explicitly in WB, and I'm not seeing it in Tornado.  That error suggests that something is not setting `Content-Length` header, but a create folder request shouldn't have a body or a content-length.

Can you try doing the same thing via `curl`?  The invocation would be:

````
$ curl -XPUT 'https://files.osf.io/v1/resources/hz9xv/providers/osfstorage/?kind=folder&name=test-name-01'
````

If the error still happens, that suggests that something is interfering with the request, either on your network or ours.   If not, then maybe something in Qt is adding a body (even something as simple as a whitespace character)?  I'm not sure, but that'll be the first step to figuring it out.

**Comment by dschreij** [comment]
I get a message that I am not authenticated as a response to the curl command:

```
curl -XPUT 'https://files.osf.io/v1/resources/hz9xv/providers/osfstorage/?kind=folder&name=test-name-01'

{"code": 401, "referrer": null, "message_long": "You must <a href=\"/login/?next=https://osf.io/api/v1/files/auth/?payload=eyJlbmMiOiAiQTI1NkdDTSIsICJhbGciOiAiZGlyIn0..pobuI2WqC9PJKAomIPuYoQ.J_4oto9OA2F8yT9qLOXGdTIrDXV49MSOON5weUMMEslOM4382YGgfL9GGlsUDx5d_U7ZQHPE2N4CpLFw1E9DWaicgOTrLYw1j8dZO1dHg-8QZ-NKWxPIs3L6FfWun2yn4u68YqIXM3Go4fAMf7f_4l2DQG9BaHZx-a2qpYbRQYnajd-7TlpHkluWwg19b_Vosw5hJXbqLl1j__c3lnww2Luoby5TL7u00wYQ2Z_ZnNepoik3VczRlv-xZLlrruiSq6RXnBYP_7dErAGS_droJkbakUVvtj9KvjjTLEbMdOj16Zs.EE_WPVXeQzpBBoB29rNRNg\">log in<\/a> to access this resource.", "message_short": "Unauthorized"}
```
which can be expected, as I am not logged in or passing a bearer token.
I will try the same using Postman if I find the time. That gives me easier ways to authenticate to the OSF API and play around with requests.

We haven't changed anything on our side since this error started occurring and is used to work, so I doubt Qt started to do something fishy with its requests, but I'll check to be sure.

**Comment by felliott** [comment]
You can pass the auth header with:

````
$ curl -H 'Authorization: Basic ashdfkkhjkdjfhasdkhf=' -XPUT 'https://files.osf.io/v1/resources/hz9xv/providers/osfstorage/?kind=folder&name=test-name-01'
````

Postman works, too (in fact, I used Postman to calculate what my basic auth token should be ^_^).

If you haven't changed anything, and we haven't changed anything, then that does suggest to me its something is monkeying w/ the request.  This should still help us figure out if its particular to the way QOSF makes requests or if it's a location thing.  This is a strange one!

**Comment by felliott** [comment]
Or you can do:

````
$ curl -H 'Authorization: Bearer asdjfha98234kadsf92' -XPUT 'https://files.osf.io/v1/resources/hz9xv/providers/osfstorage/?kind=folder&name=test-name-01'
````

to authenticate with your PAT, which you can create a https://osf.io/settings/tokens/.

**Comment by dschreij** [comment]
Sorry, still haven't had the time to dive into this, but it is still on my radar and will have a look at it soon! (hopefully this week)

**Comment by dschreij** [comment]
Although this issue is very stale, it's still relevant, and I only got around to looking into it now. I tried executing the above command with a PAT throught Postman, and that worked flawlessly. The problem thus must lie in our Qt codebase, and I will look into that.

**Comment by dschreij** [comment]
Alright, that was a relative simple fix. If you perform a PUT request to the OSF, you apparently have to explicitly specify the Content-Length parameter in the request header. Qt apparently does not set this automatically to 0 if you perform a PUT request without any data in the body. By adding a check like

```python
if data_to_send is None:
    request.setHeader(request.ContentLengthHeader, '0')
```
folder creation works again without errors.
