### ISSUE TITLE
TypeError on logout

### ISSUE THREAD

**Issue by smathot** [dschreij/QOpenScienceFramework#19]
I was using the OSF extension in OpenSesame. At some point, the extension notified me that I had to log in again. (I'm not sure why. Maybe the login had simply expired with time.) The first problem is that I still seemed to be logged in, and so the only thing I could do was click on "log out". And when I did that, the following error occurred:

```
Traceback (most recent call last):
  File "/home/sebastiaan/git/QOpenScienceFramework/QOpenScienceFramework/manager.py", line 456, in <lambda>
    lambda: self.__reply_finished(callback, *args, **kwargs))
  File "/home/sebastiaan/git/QOpenScienceFramework/QOpenScienceFramework/manager.py", line 823, in __reply_finished
    errorCallback(reply, *args, **kwargs)
TypeError: __logout_failed() got an unexpected keyword argument 'errorCallback'
```

**Comment by dschreij** [comment]
Check, I think I know what causes this and it should be relatively easy to fix. It's only probably only difficult to reproduce the error you experienced during the logout.
