### ISSUE TITLE
Bad Gateway reply for GitHub storage provider

### ISSUE THREAD

**Issue by smathot** [dschreij/QOpenScienceFramework#5]
If I log into the OSF through OpenSesame, I receive the following error message:

![image](https://cloud.githubusercontent.com/assets/594936/16338040/4370a81c-3a1a-11e6-8159-55613504d404.png)

This happens since I linked GitHub to one of my projects, so I suspect it has to do with that. 
- opensesame-extension-osf: 1.0.8
- QOpenScienceFramework: 1.1.1
- opensesame 3.1.0a45

If you want, I could give you access to the project so you can test it.

**Comment by dschreij** [comment]
I’ve also seen this before, and it usually means that they are working on the OSF side. A bad gateway is not really something we can do about. It usually means a bad redirect from their side, and judging from your link, it has to do with their connection to Github. I will have a look at it soon and see what I can do, but I don’t expect it to be much. We might want to mail Andrew or Fitz about this?

**Comment by smathot** [comment]
In that case, let's wait if the error goes away by itself. It doesn't appear to have much effect on the OSF explorer itself.

**Comment by smathot** [comment]
Fyi, the error is still there, every time I log in. It doesn't appear to do any harm, but it's quite ugly.

**Comment by dschreij** [comment]
Alright, one option is to scan for this message and simply not show it. This way we at least remove the nuisance of the notification. There still not much we can do about the error itself, because it is occurs somewhere in the OSF (Waterbutler) server and we just use their API as they describe.

**Comment by smathot** [comment]
Let's leave it then.

What we could do, though, is add the possibility to permanently silence particular messages in `QNotifications`. What do you think about that?

**Comment by dschreij** [comment]
That sounds like a good idea. We already have a timeout variable within which period a message is suppressed. What if we add the option to pass the variable 'infinite' to timeout? That would still correspond to that session in which QNotifications is used though, so every time you restart OpenSesame you will see the message again, unless you store the messages to be suppressed in a file somewhere, which seems a bit far-fetched to me.

I have posted an issue at https://github.com/CenterForOpenScience/waterbutler
