### ISSUE TITLE
Uploading dialog isn't pretty

### ISSUE THREAD

**Issue by smathot** [dschreij/QOpenScienceFramework#6]
A very minor improvement. As I was using the OSF extension to upload an EDF file (which worked beautifully and automatically!) I noticed that the upload dialog isn't very pretty: It doesn't have a name, nor an icon.

![image](https://cloud.githubusercontent.com/assets/594936/17251965/0b4bc96a-55ab-11e6-885c-b70f0e53e2db.png)

**Comment by dschreij** [comment]
I can look into this, but I’m using a default function that creates this dialog box for me, so I’m not really sure how much control I have over its appearance. I’m glad it works in any case (we didn’t test uploading EDF files before).

**Comment by dschreij** [comment]
The dialog is revamped from 1.1.6 onwards!

**Comment by smathot** [comment]
Bim!
